version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tlcc_db
    ports: ['5432:5432']
    volumes: ['pgdata:/var/lib/postgresql/data']
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    ports: ['6379:6379']
    volumes: ['redis-data:/data']
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      retries: 5

  # api:
  #   build:
  #     context: ../apps/api
  #     dockerfile: ../../infrastructure/docker/Dockerfile.api
  #   ports: ['3001:3001']
  #   environment:
  #     DATABASE_URL: postgresql://postgres:password@postgres:5432/tlcc_db?schema=public
  #     REDIS_URL: redis://redis:6379
  #   depends_on:
  #     postgres: { condition: service_healthy }
  #     redis: { condition: service_healthy }

volumes:
  pgdata:
  redis-data:
